# Generated by Django 3.2.3 on 2021-06-08 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0002_pointvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='image',
            field=models.FileField(default='products_images/banner_2_product.png', upload_to='categories'),
        ),
        migrations.AddField(
            model_name='productcategory',
            name='tax',
            field=models.FloatField(default=5.0),
        ),
        migrations.AddField(
            model_name='productsubcategory',
            name='image',
            field=models.FileField(default='products_images/banner_2_product.png', upload_to='categories'),
        ),
        migrations.AddField(
            model_name='productsubsubcategory',
            name='image',
            field=models.FileField(default='products_images/banner_2_product.png', upload_to='categories'),
        ),
    ]
