# Generated by Django 3.2.3 on 2021-06-12 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0005_variant_varientvalue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VarientValue',
            new_name='VariantValue',
        ),
        migrations.AlterModelTable(
            name='variantvalue',
            table='VariantValue',
        ),
    ]
