# Generated by Django 3.2.3 on 2021-06-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0010_commission_commissiontransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVPairValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair_value', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'PVPairValue',
            },
        ),
    ]
