# Generated by Django 3.2.3 on 2021-06-17 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0013_remove_query_assigned_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='query_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
