# Generated by Django 3.2.3 on 2021-06-19 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0014_query_query_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='PVConversionValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversion_value', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'PVConversionValue',
            },
        ),
    ]
