# Generated by Django 3.2.3 on 2021-06-24 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0015_pvconversionvalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcategory',
            name='commission',
            field=models.FloatField(default=10.0),
        ),
    ]
