# Generated by Django 3.2.3 on 2021-06-24 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0016_productcategory_commission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VendorCommission',
        ),
    ]
