# Generated by Django 3.2.3 on 2021-06-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0017_delete_vendorcommission'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='reply',
            field=models.TextField(default='No-Reply'),
        ),
    ]
