# Generated by Django 3.2.3 on 2021-06-30 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0018_query_reply'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_tax', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'Tax',
            },
        ),
        migrations.CreateModel(
            name='TaxPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('tax_current', models.FloatField(default=0.0)),
                ('tax_paid', models.FloatField(default=0.0)),
                ('tax_remaining', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'TaxPay',
            },
        ),
    ]
