# Generated by Django 3.2.3 on 2021-07-09 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0019_tax_taxpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Savings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('savings', models.FloatField(default=0.0)),
            ],
            options={
                'db_table': 'savings',
            },
        ),
    ]
