# Generated by Django 3.2.3 on 2021-07-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0020_savings'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('sub_title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=150)),
                ('image', models.FileField(upload_to='banners')),
            ],
            options={
                'db_table': 'HomeBanner',
            },
        ),
    ]
