# Generated by Django 3.2.3 on 2021-07-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0021_homebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='homebanner',
            name='link',
            field=models.CharField(default='NONE', max_length=500),
        ),
    ]
