# Generated by Django 3.2.3 on 2021-10-08 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0023_uservendorcommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_charge', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'SubscriptionCharge',
            },
        ),
    ]
