# Generated by Django 3.2.3 on 2021-10-16 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0025_auto_20211016_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptioncharge',
            name='pv_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptioncharge',
            name='vendor_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
