# Generated by Django 3.2.3 on 2021-11-19 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0026_auto_20211016_1527'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configured_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('levels', models.PositiveIntegerField()),
                ('groups', models.PositiveIntegerField()),
            ],
            options={
                'db_table': 'Level_Settings',
            },
        ),
        migrations.CreateModel(
            name='Level_Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configured_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('percent_per_level', models.FloatField()),
                ('no_of_levels', models.PositiveIntegerField()),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.level_settings')),
            ],
            options={
                'db_table': 'Level_Group',
            },
        ),
    ]
