# Generated by Django 3.2.3 on 2021-11-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0027_level_group_level_settings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='level_group',
            name='no_of_levels',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='level_group',
            name='percent_per_level',
            field=models.FloatField(default=1),
        ),
    ]
