# Generated by Django 3.2.3 on 2021-11-22 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0028_auto_20211119_1337'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing_Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configured_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('vendor_commission', models.FloatField(default=1)),
                ('pv_percent', models.PositiveIntegerField(default=1)),
            ],
            options={
                'db_table': 'Billing_Config',
            },
        ),
    ]
