# Generated by Django 3.2.3 on 2021-11-22 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0029_billing_config'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_config',
            name='pv_percent',
            field=models.FloatField(default=1),
        ),
    ]
