# Generated by Django 3.2.3 on 2021-11-22 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0030_alter_billing_config_pv_percent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billing_config',
            old_name='vendor_commission',
            new_name='admin_commission',
        ),
    ]
