# Generated by Django 3.2.3 on 2021-11-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0033_alter_query_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriptioncharge',
            name='subscription_charge',
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='one_month_subscription_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='six_month_subscription_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='three_month_subscription_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='subscriptioncharge',
            name='twelve_month_subscription_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subscriptioncharge',
            name='pv_percentage',
            field=models.FloatField(default=10.0),
        ),
        migrations.AlterField(
            model_name='subscriptioncharge',
            name='vendor_percentage',
            field=models.FloatField(default=10.0),
        ),
    ]
