# Generated by Django 4.0.2 on 2022-07-04 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_auto_20211127_1254'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeadershipBonusCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=10.0)),
            ],
            options={
                'db_table': 'UserLeadershipBonusCommission',
            },
        ),
    ]
