# Generated by Django 4.0.2 on 2022-07-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0035_userleadershipbonuscommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=10.0)),
            ],
            options={
                'db_table': 'CarFund',
            },
        ),
        migrations.CreateModel(
            name='DirectorshipFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=10.0)),
            ],
            options={
                'db_table': 'DirectorshipFund',
            },
        ),
        migrations.CreateModel(
            name='HouseFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=10.0)),
            ],
            options={
                'db_table': 'HouseFund',
            },
        ),
        migrations.CreateModel(
            name='TravelFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=10.0)),
            ],
            options={
                'db_table': 'TravelFund',
            },
        ),
    ]
