# Generated by Django 4.0.2 on 2022-07-06 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0036_carfund_directorshipfund_housefund_travelfund'),
    ]

    operations = [
        migrations.AddField(
            model_name='carfund',
            name='target',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='directorshipfund',
            name='target',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='housefund',
            name='target',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='travelfund',
            name='target',
            field=models.PositiveIntegerField(default=100000),
        ),
        migrations.AddField(
            model_name='userleadershipbonuscommission',
            name='target',
            field=models.PositiveIntegerField(default=100000),
        ),
    ]
