# Generated by Django 4.0.2 on 2022-07-07 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0039_aboutus_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutus',
            name='image',
        ),
    ]
