# Generated by Django 4.0.2 on 2022-07-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0040_remove_aboutus_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='image',
            field=models.ImageField(null=True, upload_to='about_us'),
        ),
    ]
