# Generated by Django 4.0.2 on 2022-07-07 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0041_aboutus_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='blog')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Blog',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='gallery')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Gallery',
            },
        ),
    ]
