# Generated by Django 4.0.2 on 2022-07-07 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0042_blog_gallery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='banner')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Banner',
            },
        ),
    ]
