# Generated by Django 4.0.2 on 2022-07-07 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0043_banner'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
