# Generated by Django 4.0.2 on 2022-07-09 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0044_delete_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectReferalCommission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.FloatField(default=10.0)),
            ],
            options={
                'db_table': 'DirectReferalCommission',
            },
        ),
    ]
