# Generated by Django 4.0.2 on 2022-07-11 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0045_directreferalcommission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeFooterBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.FileField(upload_to='banners')),
            ],
            options={
                'db_table': 'HomeFooterBanner',
            },
        ),
    ]
