# Generated by Django 4.0.2 on 2022-07-12 07:17

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0048_remove_aboutus_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
