# Generated by Django 4.0.2 on 2022-07-12 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0049_aboutus_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='content',
        ),
    ]
