from django.contrib import admin
from django.urls import path
from admin_app.views import *
from admin_app.utils import *

urlpatterns = [
    path('dashboard', admin_dashboard),
    path('show', admin_show),
    path('productcategories', admin_product_categories),
    path('', admin_login),
    path('productcategories', admin_product_categories),
    path('admin_pv', admin_pv_wallet),
    path('deleteproductcategory', admin_delete_product_category),
    path('productsubcategories', admin_product_sub_categories),
    path('deleteproductsubcategory', admin_delete_product_sub_category),
    path('productsubsubcategories', admin_product_sub_sub_categories),
    path('deleteproductsubsubcategory', admin_delete_product_sub_sub_category),
    path('kycrequests', admin_kyc_requests),
    path('activatevendor', admin_activate_vendor),
    path('point/', admin_point_value),
    path('createlink', admin_create_link),
    path('generatelink', admin_generate_link),
    path('undertrees', admin_under_trees),
    path('deliverycharges', admin_delivery_charges),
    path('kycvendors', admin_kyc_vendors),
    path('vendorprofile', admin_vendor_profile),
    path('paymentinfo', admin_payment_info),
    path('orders', admin_orders),
    path('setpvpair', admin_pvpairvalue),
    path('leadershipbonus', admin_leadership_bonus_set),
    path('housefund', admin_house_fund_set),
    path('carfund', admin_car_fund_set),
    path('directorshipfund', admin_directorship_fund_set),
    path('travelfund', admin_travel_fund_set),
    path('sendmoney', admin_send_money),
    path('withdraw', admin_withdraw),
    path('changewithdrawstatus', admin_change_withdraw_status),
    path('query', admin_query),
    path('queryresult', admin_query_result),
    path('changequerystatus', admin_change_query_status),
    path('setpvconversion', admin_set_pv_conversion),
    path('productapproval', admin_product_approval),
    path('activateproduct', admin_activate_product),
    path('sendqueryreply', admin_query_send_reply),
    path('wallet_details', wallet_details),
    
    path('tax', admin_taxation),
    path('users', admin_users),
    path('users/delete', admin_users_delete),
    #path for User commission for refered vendor
    path('uservendorcommission', user_vendor_commission),
    path('level/settings/', admin_level_settings),
    path('level/fetchgroups/', admin_fetch_groups),
    path('level/edit/group/', admin_edit_group),
    path('minmumcartvalue/', admin_min_cart_value),
    path('billing/config/', admin_billing_config),
    path('product/reject/', admin_reject_product),
    path('product/update/', admin_update_product),
    path('gst_log/', admin_gst_log),
    path('tds_log/', admin_tds_withdraw),
    path('contact', contact),
    path('terms', terms),
    path('privacy', privacy),
    path('about-us', admin_about_us),
    path('gallery', admin_gallery),
    path('blog', admin_blog),
    path('banner', admin_banner),
    path('direct-referal', admin_direct_referal),
#trial

    
]