# Generated by Django 3.2.3 on 2021-06-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_remove_userdata_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='question',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
