# Generated by Django 3.2.3 on 2021-06-08 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vendor_app', '0008_auto_20210605_1134'),
        ('user_app', '0003_userdata_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.FloatField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
        migrations.CreateModel(
            name='CartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('per_item_cost', models.FloatField()),
                ('total_cost', models.FloatField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user_app.cart')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productcolor', to='vendor_app.productcolors')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='vendor_app.product')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productsize', to='vendor_app.productsizes')),
            ],
            options={
                'db_table': 'CartItems',
            },
        ),
    ]
