# Generated by Django 3.2.3 on 2021-06-08 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0005_auto_20210608_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax',
            field=models.FloatField(default=0),
        ),
    ]
