# Generated by Django 3.2.3 on 2021-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0008_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='delivery_charges',
            field=models.FloatField(default=0),
        ),
    ]
