# Generated by Django 3.2.3 on 2021-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0009_cart_delivery_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='self_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
