# Generated by Django 3.2.3 on 2021-06-11 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0011_auto_20210611_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='pv',
            field=models.FloatField(default=0.0),
        ),
    ]
