# Generated by Django 3.2.3 on 2021-06-12 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0013_auto_20210612_1618'),
        ('user_app', '0013_alter_pvtransactions_previous_pv'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='color',
        ),
        migrations.RemoveField(
            model_name='cartitems',
            name='size',
        ),
        migrations.CreateModel(
            name='CartItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.cart')),
                ('cartitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.cartitems')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.productvariant')),
            ],
            options={
                'db_table': 'CartItemVariant',
            },
        ),
    ]
