# Generated by Django 3.2.3 on 2021-06-17 13:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0015_paymentinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserWithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('status', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdraw_request', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserWithdrawRequest',
            },
        ),
    ]
