# Generated by Django 3.2.3 on 2021-06-17 13:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0016_userwithdrawrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('right_pv', models.FloatField(default=0.0)),
                ('left_pv', models.FloatField(default=0.0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userpv', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserPV',
            },
        ),
    ]
