# Generated by Django 3.2.3 on 2021-06-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0017_userpv'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentinfo',
            name='aadhar',
            field=models.FileField(default=1, upload_to='user_pancard_image'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paymentinfo',
            name='pan',
            field=models.FileField(default=1, upload_to='user_pancard_image'),
            preserve_default=False,
        ),
    ]
