# Generated by Django 3.2.3 on 2021-09-23 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0023_auto_20210923_1133'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0020_auto_20210707_1205'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserVendorRelation',
            fields=[
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='vendor_app.vendor')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'UserVendorRelation',
            },
        ),
    ]
