# Generated by Django 3.2.3 on 2021-10-08 07:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user_app', '0022_userdata_subscribed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='member', serialize=False, to='auth.user')),
                ('subscribed_on', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Membership',
            },
        ),
    ]
