# Generated by Django 3.2.3 on 2021-10-08 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0024_memberip_receipt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberip_receipt',
            old_name='vendor',
            new_name='user',
        ),
    ]
