# Generated by Django 3.2.3 on 2021-11-11 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0026_usersubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='pvtransactions',
            name='plan',
            field=models.CharField(default='Binary', max_length=100),
        ),
    ]
