# Generated by Django 3.2.3 on 2021-11-17 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0027_pvtransactions_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpv',
            name='level_pv',
            field=models.FloatField(default=0.0),
        ),
    ]
