# Generated by Django 3.2.3 on 2021-11-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0028_userpv_level_pv'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscription',
            name='months',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
