# Generated by Django 3.2.3 on 2021-11-20 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0030_billing_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_request',
            name='plan',
            field=models.CharField(default='Level', max_length=100),
        ),
    ]
