# Generated by Django 3.2.3 on 2021-11-27 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0031_billing_request_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpv',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userpv', to=settings.AUTH_USER_MODEL),
        ),
    ]
