# Generated by Django 3.2.3 on 2021-06-10 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0008_auto_20210605_1134'),
        ('user_app', '0008_address_default'),
        ('main_app', '0002_mlm_mlmadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateTimeField()),
                ('subtotal', models.FloatField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.address')),
            ],
            options={
                'db_table': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('per_item_cost', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('tax', models.FloatField()),
                ('total', models.FloatField()),
                ('delivery_status', models.CharField(default='Order Placed', max_length=50)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproductcolor', to='vendor_app.productcolors')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.orders')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderproduct', to='vendor_app.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orderproductsize', to='vendor_app.productsizes')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.store')),
            ],
            options={
                'db_table': 'OrderItems',
            },
        ),
    ]
