# Generated by Django 3.2.3 on 2021-06-10 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_orders_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='point_value',
            field=models.FloatField(default=0.0),
        ),
    ]
