# Generated by Django 3.2.3 on 2021-06-10 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_orders_point_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='deliver_charges',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='orders',
            name='self_pickup',
            field=models.BooleanField(default=False),
        ),
    ]
