# Generated by Django 3.2.3 on 2021-06-10 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_auto_20210610_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='deliver_charges',
            new_name='delivery_charges',
        ),
    ]
