# Generated by Django 3.2.3 on 2021-06-10 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_rename_deliver_charges_orders_delivery_charges'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='delivered_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
