# Generated by Django 3.2.3 on 2021-06-12 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0013_auto_20210612_1618'),
        ('main_app', '0009_orderitems_delivered_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItemVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.orders')),
                ('orderitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.orderitems')),
                ('product_variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.productvariant')),
            ],
            options={
                'db_table': 'OrderItemVariant',
            },
        ),
    ]
