# Generated by Django 3.2.3 on 2021-06-12 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_orderitemvariant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='color',
        ),
        migrations.RemoveField(
            model_name='orderitems',
            name='size',
        ),
    ]
