# Generated by Django 3.2.3 on 2021-06-15 12:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_app', '0014_auto_20210612_1724'),
        ('main_app', '0011_auto_20210612_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.address')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_app.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RazorpayOrder',
            },
        ),
    ]
