# Generated by Django 3.2.3 on 2021-06-16 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20210615_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='razorpaytransaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.razorpaytransaction'),
        ),
    ]
