# Generated by Django 3.2.3 on 2021-06-16 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_wallet_wallettransaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='current_balance',
            field=models.FloatField(default=0.0),
        ),
    ]
