# Generated by Django 3.2.3 on 2021-11-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0018_notification_read'),
    ]

    operations = [
        migrations.CreateModel(
            name='Min_Amount_For_Free_Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
            ],
            options={
                'db_table': 'Min_Amount_For_Free_Delivery',
            },
        ),
    ]
