# Generated by Django 3.2.3 on 2021-12-07 06:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_min_amount_for_free_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='GST_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('gst_amt', models.FloatField(default=0.0)),
                ('orders', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.orderitems')),
            ],
            options={
                'db_table': 'GST_Log',
            },
        ),
    ]
