# Generated by Django 3.2.3 on 2021-12-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_gst_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gst_log',
            name='transaction_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
