# Generated by Django 3.2.3 on 2021-12-10 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_gst_log_transaction_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TDS_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('tds_amt', models.FloatField(default=0.0)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.wallet')),
            ],
            options={
                'db_table': 'TDS_Log',
            },
        ),
    ]
