# Generated by Django 3.2.3 on 2021-12-10 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0022_tds_log'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TDS_Log',
        ),
    ]
