# Generated by Django 3.2.3 on 2021-12-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_tds_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='tds_log',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
    ]
