# Generated by Django 3.2.3 on 2022-06-14 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0025_tds_log_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='privacypolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('policy', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Privacy and Policy',
            },
        ),
        migrations.CreateModel(
            name='termsandcondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('contain', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Terms and Condition',
            },
        ),
    ]
