# Generated by Django 3.2.3 on 2022-06-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0026_privacypolicy_termsandcondition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='policy',
        ),
        migrations.RemoveField(
            model_name='termsandcondition',
            name='contain',
        ),
    ]
