# Generated by Django 3.2.3 on 2022-06-14 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0027_auto_20220614_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='content',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
