# Generated by Django 4.0.2 on 2022-06-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0028_auto_20220614_1921'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('contact_no', models.PositiveIntegerField()),
                ('gmail_id', models.CharField(max_length=200)),
                ('facbook_id', models.CharField(max_length=200)),
                ('instagram_id', models.CharField(max_length=200)),
                ('twitter_id', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Company_Details',
            },
        ),
    ]
