# Generated by Django 4.0.2 on 2022-06-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0029_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='cancelled_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
