# Generated by Django 4.0.2 on 2022-06-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0030_orderitems_cancelled_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='cancellation_reason',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
