# Generated by Django 4.0.2 on 2022-07-13 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0031_orderitems_cancellation_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='privacypolicy',
            name='content',
        ),
    ]
