# Generated by Django 4.0.2 on 2022-07-13 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0032_remove_privacypolicy_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='termsandcondition',
            name='content',
        ),
    ]
