# Generated by Django 4.0.2 on 2022-07-13 13:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0033_remove_termsandcondition_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='privacypolicy',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='termsandcondition',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
