# Generated by Django 4.0.2 on 2022-07-26 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0035_pv_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletTransferApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.BooleanField(default=True)),
                ('vendor', models.BooleanField(default=True)),
                ('lastupdate_time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='WalletTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('senderusername', models.CharField(max_length=256)),
                ('reciverusername', models.CharField(max_length=256)),
                ('transection_id', models.CharField(max_length=256, unique=True)),
                ('amount', models.IntegerField(default=0)),
                ('transection_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
