# Generated by Django 3.2.3 on 2021-06-01 10:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=300)),
                ('registration_number', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('closing_day', models.CharField(max_length=50)),
                ('closing_time', models.CharField(max_length=50)),
                ('opening_time', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=10)),
                ('zipcode', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=10)),
                ('longitude', models.CharField(max_length=200)),
                ('latitude', models.CharField(max_length=200)),
                ('gender', models.CharField(max_length=200)),
                ('store_created', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Vendor',
            },
        ),
        migrations.CreateModel(
            name='VendorDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_aadhar', models.CharField(max_length=20)),
                ('front_aadhar', models.FileField(upload_to='store_seller_aadhar_image')),
                ('back_aadhar', models.FileField(null=True, upload_to='store_seller_aadhar_image')),
                ('store_gst', models.CharField(max_length=50)),
                ('pancard', models.CharField(max_length=50)),
                ('pancard_image', models.FileField(upload_to='store_seller_pancard_image')),
                ('shiping_policy', models.FileField(null=True, upload_to='shiping_policy')),
                ('return_policy', models.FileField(null=True, upload_to='return_policy')),
                ('bank_account_number', models.CharField(max_length=50)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_ifsc', models.CharField(max_length=100)),
                ('bank_passbook', models.FileField(upload_to='store_bank_passbook')),
                ('razorpay_id', models.CharField(max_length=200, null=True)),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.store')),
                ('vendor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.vendor')),
            ],
            options={
                'db_table': 'VendorDocs',
            },
        ),
        migrations.CreateModel(
            name='StoreImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='store_logo')),
                ('banner', models.ImageField(upload_to='store_banner')),
                ('image', models.ImageField(upload_to='store_image')),
                ('store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.store')),
            ],
            options={
                'db_table': 'StoreImages',
            },
        ),
        migrations.AddField(
            model_name='store',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.vendor'),
        ),
    ]
