# Generated by Django 3.2.3 on 2021-06-02 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0003_remove_vendordocs_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='doc_submitted',
            field=models.BooleanField(default=False),
        ),
    ]
