# Generated by Django 3.2.3 on 2021-06-02 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0004_vendor_doc_submitted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='category',
        ),
    ]
