# Generated by Django 3.2.3 on 2021-06-05 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0007_auto_20210603_1815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendor',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
