# Generated by Django 3.2.3 on 2021-06-11 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0008_auto_20210605_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='Varient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.store')),
            ],
            options={
                'db_table': 'Varient',
            },
        ),
        migrations.CreateModel(
            name='VarientValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=50)),
                ('varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.varient')),
            ],
            options={
                'db_table': 'VarientValues',
            },
        ),
        migrations.CreateModel(
            name='ProductVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.product')),
                ('varient_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.varientvalues')),
            ],
            options={
                'db_table': 'ProductVarientValues',
            },
        ),
    ]
