# Generated by Django 3.2.3 on 2021-06-11 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0004_deliverycharge'),
        ('vendor_app', '0009_productvarient_varient_varientvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategoryVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.productsubcategory')),
                ('varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.varient')),
            ],
            options={
                'db_table': 'SubCategoryVarient',
            },
        ),
    ]
