# Generated by Django 3.2.3 on 2021-06-12 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0010_subcategoryvarient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategoryvarient',
            name='subcategory',
        ),
        migrations.RemoveField(
            model_name='subcategoryvarient',
            name='varient',
        ),
        migrations.RemoveField(
            model_name='varient',
            name='store',
        ),
        migrations.RemoveField(
            model_name='varientvalues',
            name='varient',
        ),
        migrations.DeleteModel(
            name='ProductVarient',
        ),
        migrations.DeleteModel(
            name='SubCategoryVarient',
        ),
        migrations.DeleteModel(
            name='Varient',
        ),
        migrations.DeleteModel(
            name='VarientValues',
        ),
    ]
