# Generated by Django 3.2.3 on 2021-06-12 09:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_variantvalue_variant'),
        ('vendor_app', '0011_auto_20210612_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_stock', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.product')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_app.variantvalue')),
            ],
            options={
                'db_table': 'ProductVariant',
            },
        ),
    ]
