# Generated by Django 3.2.3 on 2021-06-12 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0007_alter_variantvalue_variant'),
        ('vendor_app', '0012_productvariant'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='variant_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.variantvalue'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.variant'),
        ),
    ]
