# Generated by Django 3.2.3 on 2021-06-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0016_productrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsizes',
            name='product',
        ),
        migrations.DeleteModel(
            name='ProductColors',
        ),
        migrations.DeleteModel(
            name='ProductSizes',
        ),
    ]
