# Generated by Django 3.2.3 on 2021-06-28 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0018_vendorwithdrawrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimages',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='vendor_app.store'),
        ),
    ]
