# Generated by Django 3.2.3 on 2021-07-08 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0019_alter_storeimages_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeimages',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.store'),
        ),
    ]
