# Generated by Django 3.2.3 on 2021-09-18 11:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0020_alter_storeimages_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.FloatField(default=0.0)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.vendor')),
            ],
            options={
                'db_table': 'BusinessLimit',
            },
        ),
        migrations.CreateModel(
            name='BusinessLimitTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField()),
                ('transaction_name', models.CharField(max_length=100)),
                ('transaction_type', models.CharField(choices=[('CREDIT', 'CREDIT'), ('DEBIT', 'DEBIT')], max_length=20)),
                ('transaction_amount', models.FloatField()),
                ('previous_amount', models.FloatField()),
                ('remaining_amount', models.FloatField()),
                ('business_imit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.businesslimit')),
            ],
            options={
                'db_table': 'BusinessLimitTransaction',
            },
        ),
    ]
