# Generated by Django 3.2.3 on 2021-09-21 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0021_businesslimit_businesslimittransaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businesslimit',
            old_name='balance',
            new_name='current_balance',
        ),
        migrations.RenameField(
            model_name='businesslimittransaction',
            old_name='business_imit',
            new_name='business_limit',
        ),
    ]
