# Generated by Django 3.2.3 on 2021-09-23 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0022_auto_20210921_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recharge_Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateTimeField(auto_now=True)),
                ('razorpay_order_id', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('amount', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendor_app.vendor')),
            ],
            options={
                'db_table': 'Recharge_Receipt',
            },
        ),
        migrations.AddField(
            model_name='businesslimittransaction',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vendor_app.recharge_receipt'),
        ),
    ]
