# Generated by Django 3.2.3 on 2021-09-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0023_auto_20210923_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendordocs',
            name='back_aadhar',
            field=models.FileField(blank=True, null=True, upload_to='store_seller_aadhar_image'),
        ),
        migrations.AlterField(
            model_name='vendordocs',
            name='front_aadhar',
            field=models.FileField(blank=True, null=True, upload_to='store_seller_aadhar_image'),
        ),
        migrations.AlterField(
            model_name='vendordocs',
            name='vendor_aadhar',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
