# Generated by Django 3.2.3 on 2021-10-16 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0026_usersubscription'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserSubscription',
        ),
    ]
