# Generated by Django 3.2.3 on 2021-11-11 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0027_delete_usersubscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businesslimit',
            name='vendor',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_limit', to='vendor_app.vendor'),
        ),
    ]
