# Generated by Django 3.2.3 on 2021-11-18 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0028_alter_businesslimit_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptionrequest',
            name='amount',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='usersubscriptionrequest',
            name='month',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
