# Generated by Django 3.2.3 on 2021-12-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0029_auto_20211118_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_rejection',
            field=models.BooleanField(default=False),
        ),
    ]
