# Generated by Django 3.2.3 on 2021-12-08 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0030_auto_20211201_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='mrp',
            field=models.FloatField(default=0.0),
        ),
    ]
