# Generated by Django 3.2.3 on 2021-12-11 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0031_product_mrp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendordocs',
            old_name='back_aadhar',
            new_name='back_idproof',
        ),
        migrations.RenameField(
            model_name='vendordocs',
            old_name='front_aadhar',
            new_name='front_idproof',
        ),
        migrations.RenameField(
            model_name='vendordocs',
            old_name='vendor_aadhar',
            new_name='vendor_idproof',
        ),
        migrations.AddField(
            model_name='vendordocs',
            name='store_msme',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vendordocs',
            name='store_gst',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
