# Generated by Django 3.2.3 on 2022-06-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('admin_app', '0034_auto_20211127_1254'),
        ('vendor_app', '0032_auto_20211211_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='variant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='admin_app.variant'),
        ),
    ]
