# Generated by Django 4.0.2 on 2022-06-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0035_product_discount_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='best_seller',
            field=models.BooleanField(default=False),
        ),
    ]
