# Generated by Django 4.0.2 on 2022-07-08 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0037_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='special_offer',
            field=models.BooleanField(default=False),
        ),
    ]
