# Generated by Django 4.0.2 on 2022-07-12 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0038_product_special_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
    ]
