# Generated by Django 4.0.2 on 2022-07-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_app', '0040_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
